version: '3.8'

services:
  # The Database Service
  postgres:
    image: postgres:16-alpine
    container_name: jobber_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      # This creates the default DB for your Auth service
      POSTGRES_DB: jobber_auth
    volumes:
      # Persist data so you don't lose users when you restart the container
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
